"""user - short_url

Revision ID: c3acab244902
Revises: b3586fa7ed3c
Create Date: 2024-05-03 12:20:05.982524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3acab244902'
down_revision: Union[str, None] = 'b3586fa7ed3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uix_short_url_user_id', 'short_url', ['short_url', 'user_id'])
    op.create_foreign_key(None, 'short_url', 'user', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_url', type_='foreignkey')
    op.drop_constraint('uix_short_url_user_id', 'short_url', type_='unique')
    op.drop_column('short_url', 'user_id')
    # ### end Alembic commands ###
