"""init_migration

Revision ID: f58cd6ad6a9f
Revises: 184f2eb199a9
Create Date: 2024-05-13 17:40:05.626348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58cd6ad6a9f'
down_revision: Union[str, None] = '184f2eb199a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('original_short_urls', sa.Column('counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('original_short_urls', 'counter')
    # ### end Alembic commands ###
